name: deploy_cloud_run
description: Deploy to GCP Cloud Run

inputs:
  service_account_json:
    required: true
    description: "GCP Service Account JSON key"
  image_name:
    required: true
    description: "Docker image name"
  app_name:
    required: true
    description: "Cloud Run app name"
  ssh-key:
    required: true
    description: "ssh key"

runs:
  using: "composite"
  steps:

    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ inputs.service_account_json }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: 🔑 Generate keys
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ inputs.ssh-key }}

    - name: 🔐 Login Docker
      shell: bash
      run: gcloud auth configure-docker --quiet

    - name: 🔨 Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: 🐳  Build Docker image
      uses: docker/build-push-action@v5
      with:
        load: true
        tags: ${{ inputs.image_name }}
        ssh: default
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: 🚚 Push Docker image
      shell: bash
      run: docker push ${{ inputs.image_name }}

    - name: 🚚 Deploy Docker image
      shell: bash
      run: |
        gcloud run deploy ${{ inputs.app_name }} \
        --image ${{ inputs.image_name }} \
        --region us-east1 \
        --platform managed \
        --port=80
