version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: be-links-postgres
    environment:
      POSTGRES_DB: be-links
      POSTGRES_USER: felipe
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: